# Generated by Django 4.2 on 2023-05-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='имя')),
                ('second_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('М ', 'мУЖСКОЙ'), ('Ж', 'женщина')], default=('М ', 'мУЖСКОЙ'), max_length=255, verbose_name='Пол')),
                ('lesson_count', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
