# Generated by Django 4.2.1 on 2023-05-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0002_match_player_team_tournament_delete_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'матчи', 'verbose_name_plural': 'матчи'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'игрок', 'verbose_name_plural': 'игроки'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'teams'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
    ]
