# Generated by Django 4.2.1 on 2023-05-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0003_alter_match_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'матч', 'verbose_name_plural': 'матчи'},
        ),
    ]
